version: '2'
services:
  flina-file-server:
    image: dql19991112/flina-file-server:1.0.1
    container_name: flina-file-server
    volumes:
      - ./application.yml:/app/application.yml
    network_mode: "host"
