version: '3'
services:
  flina-rest-server:
    image: dql19991112/flina-rest-server:1.0.0
    container_name: flina-rest-server
    volumes:
      - ./application.yml:/app/application.yml
    network_mode: "host"
