version: '3'
services:
  flina-auth-server:
    image: dql19991112/flina-auth-server:1.0.1
    container_name: flina-auth-server
    volumes:
      - ./application.yml:/app/application.yml
    network_mode: "host"